name: Extract PowerQuery Functions Schema
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 1 */1 *'  # Run monthly on the 1st day of each month
  push:
    branches: [ main ]
    paths:
      - 'process/dox.pbix'
      - '.github/scripts/generate-doc-output.ps1'
      - '.github/workflows/doc.yaml'

jobs:
  setup-and-process:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup environment dependencies
        run: |
          # Install Power BI Desktop via chocolatey (MSI version)
          Write-Host "📦 Installing Power BI Desktop via Chocolatey..."
          
          try {
            # Install with verbose output and timeout
            $installResult = choco install powerbi --ignore-checksums --timeout 600 --yes
            
            if ($LASTEXITCODE -eq 0) {
              Write-Host "✅ Chocolatey installation completed successfully"
            } else {
              Write-Host "⚠️ Chocolatey installation may have issues (exit code: $LASTEXITCODE)"
              Write-Host "Installation output: $installResult"
            }
            
            # Wait for installation to complete
            Write-Host "⏳ Waiting for installation to finalize..."
            Start-Sleep -Seconds 45
            
            # Verify installation was successful
            $pbiMsiPath = "C:\Program Files\Microsoft Power BI Desktop\bin\PBIDesktop.exe"
            if (Test-Path $pbiMsiPath) {
              Write-Host "✅ Power BI Desktop MSI successfully installed at: $pbiMsiPath"
              
              # Test if executable works
              try {
                $version = & $pbiMsiPath /? 2>&1
                Write-Host "✅ Power BI Desktop executable is functional"
              } catch {
                Write-Host "⚠️ Power BI Desktop executable may have issues: $_"
              }
            } else {
              Write-Host "⚠️ MSI version not found at expected location after installation"
              Write-Host "This might be normal if Store version is already installed"
            }
            
          } catch {
            Write-Error "❌ Failed to install Power BI Desktop: $_"
            Write-Host "Continuing anyway - may use existing installation..."
          }
          
          # Install SqlServer PowerShell module
          Write-Host "📦 Installing SqlServer PowerShell module..."
          Install-Module -Name SqlServer -Force -Scope AllUsers -AllowClobber
          
          # Import the module to verify installation
          Import-Module SqlServer
          
          # Verify Invoke-ASCmd is available
          Get-Command Invoke-ASCmd

      - name: Verify environment prerequisites
        run: |
          Write-Host "🔍 Verifying environment setup..."
          
          # Import SqlServer module (needed for each step)
          Import-Module SqlServer -Force
          
          # Check if SqlServer module is now loaded
          if (Get-Module -Name SqlServer) {
            Write-Host "✅ SqlServer module is loaded"
          } else {
            Write-Error "❌ SqlServer module not loaded"
            exit 1
          }
          
          # Check if Invoke-ASCmd is available
          if (Get-Command Invoke-ASCmd -ErrorAction SilentlyContinue) {
            Write-Host "✅ Invoke-ASCmd command is available"
          } else {
            Write-Error "❌ Invoke-ASCmd command not found"
            exit 1
          }
          
          # Check if dox.pbix exists
          $pbixPath = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath "process\dox.pbix"
          if (Test-Path $pbixPath) {
            Write-Host "✅ Found dox.pbix file at: $pbixPath"
          } else {
            Write-Error "❌ dox.pbix file not found at: $pbixPath"
            exit 1
          }
          
          # Check if extraction script exists
          $scriptPath = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath ".github\scripts\generate-doc-output.ps1"
          if (Test-Path $scriptPath) {
            Write-Host "✅ Found extraction script at: $scriptPath"
          } else {
            Write-Error "❌ Extraction script not found at: $scriptPath"
            exit 1
          }
          
          # Check Power BI Desktop installation and determine path
          $pbiMsiPath = "C:\Program Files\Microsoft Power BI Desktop\bin\PBIDesktop.exe"
          $pbiStorePath = "shell:AppsFolder\Microsoft.MicrosoftPowerBIDesktop_8wekyb3d8bbwe!Microsoft.MicrosoftPowerBIDesktop"
          
          Write-Host "🔍 Checking for Power BI Desktop installations..."
          
          if (Test-Path $pbiMsiPath) {
            Write-Host "✅ Power BI Desktop MSI version found at: $pbiMsiPath"
            $env:PBI_DESKTOP_PATH = $pbiMsiPath
            $env:PBI_DESKTOP_TYPE = "MSI"
            
            # Persist to GitHub environment for next steps
            "PBI_DESKTOP_PATH=$pbiMsiPath" | Out-File -FilePath $env:GITHUB_ENV -Append
            "PBI_DESKTOP_TYPE=MSI" | Out-File -FilePath $env:GITHUB_ENV -Append
          } else {
            Write-Host "ℹ️ MSI version not found at expected path"
            
            # Check for Store version
            try {
              $storeApps = Get-AppxPackage -Name "*PowerBI*" -ErrorAction SilentlyContinue
              if ($storeApps) {
                Write-Host "✅ Power BI Desktop Store version found: $($storeApps.Name)"
                $env:PBI_DESKTOP_PATH = $pbiStorePath
                $env:PBI_DESKTOP_TYPE = "STORE"
                
                # Persist to GitHub environment for next steps
                "PBI_DESKTOP_PATH=$pbiStorePath" | Out-File -FilePath $env:GITHUB_ENV -Append
                "PBI_DESKTOP_TYPE=STORE" | Out-File -FilePath $env:GITHUB_ENV -Append
              } else {
                Write-Host "ℹ️ Store version not found either"
                
                # Try to find PBI Desktop by searching common install locations
                $possiblePaths = @(
                  "C:\Program Files\Microsoft Power BI Desktop\bin\PBIDesktop.exe",
                  "${env:LOCALAPPDATA}\Microsoft\WindowsApps\PBIDesktop.exe"
                )
                
                $foundPath = $null
                foreach ($path in $possiblePaths) {
                  if (Test-Path $path) {
                    $foundPath = $path
                    break
                  }
                }
                
                if ($foundPath) {
                  Write-Host "✅ Power BI Desktop found at: $foundPath"
                  $env:PBI_DESKTOP_PATH = $foundPath
                  $env:PBI_DESKTOP_TYPE = "CUSTOM"
                  
                  # Persist to GitHub environment for next steps
                  "PBI_DESKTOP_PATH=$foundPath" | Out-File -FilePath $env:GITHUB_ENV -Append
                  "PBI_DESKTOP_TYPE=CUSTOM" | Out-File -FilePath $env:GITHUB_ENV -Append
                } else {
                  Write-Error "❌ No Power BI Desktop installation found in any expected location"
                  Write-Host "Searched locations:"
                  $possiblePaths | ForEach-Object { Write-Host "  - $_" }
                  exit 1
                }
              }
            } catch {
              Write-Error "❌ Error checking for Power BI Desktop: $_"
              exit 1
            }
          }
          
          Write-Host "🎉 All prerequisites verified successfully!"
          Write-Host "📍 Using Power BI Desktop: $($env:PBI_DESKTOP_TYPE) at $($env:PBI_DESKTOP_PATH)"

      - name: Extract PowerQuery functions schema
        run: |
          # Import SqlServer module at start of extraction
          Import-Module SqlServer -Force
          
          # Set English locale
          $env:PQ_UICultureOverride = "en"
          Write-Host "Set locale to English (en)"

          # Verify we have the Power BI Desktop path - fallback detection if needed
          if (-not $env:PBI_DESKTOP_PATH -or -not $env:PBI_DESKTOP_TYPE) {
            Write-Host "⚠️ Power BI Desktop environment variables not found, performing fallback detection..."
            
            $pbiMsiPath = "C:\Program Files\Microsoft Power BI Desktop\bin\PBIDesktop.exe"
            
            if (Test-Path $pbiMsiPath) {
              Write-Host "✅ Found Power BI Desktop MSI at: $pbiMsiPath"
              $env:PBI_DESKTOP_PATH = $pbiMsiPath
              $env:PBI_DESKTOP_TYPE = "MSI"
            } else {
              # Try to find in Windows Apps
              $windowsAppsPath = "${env:LOCALAPPDATA}\Microsoft\WindowsApps\PBIDesktop.exe"
              if (Test-Path $windowsAppsPath) {
                Write-Host "✅ Found Power BI Desktop in Windows Apps: $windowsAppsPath"
                $env:PBI_DESKTOP_PATH = $windowsAppsPath
                $env:PBI_DESKTOP_TYPE = "WINDOWSAPPS"
              } else {
                Write-Error "❌ Could not locate Power BI Desktop installation"
                exit 1
              }
            }
          }

          # Start Power BI Desktop with the dox.pbix file
          $pbixPath = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath "process\dox.pbix"
          Write-Host "🚀 Starting Power BI Desktop ($($env:PBI_DESKTOP_TYPE)) with file: $pbixPath"
          Write-Host "📍 Using executable: $($env:PBI_DESKTOP_PATH)"
          
          try {
            if ($env:PBI_DESKTOP_TYPE -eq "MSI" -or $env:PBI_DESKTOP_TYPE -eq "CUSTOM" -or $env:PBI_DESKTOP_TYPE -eq "WINDOWSAPPS") {
              # Launch MSI, custom, or Windows Apps version directly
              $process = Start-Process -FilePath $env:PBI_DESKTOP_PATH -ArgumentList "`"$pbixPath`"" -PassThru -WindowStyle Hidden
              if ($process) {
                Write-Host "✅ Power BI Desktop ($($env:PBI_DESKTOP_TYPE)) launched with PID: $($process.Id)"
              } else {
                Write-Host "✅ Power BI Desktop ($($env:PBI_DESKTOP_TYPE)) launch initiated (no PID returned)"
              }
            } elseif ($env:PBI_DESKTOP_TYPE -eq "STORE") {
              # Launch Store version - this is trickier and may not return a process object
              Start-Process -FilePath $env:PBI_DESKTOP_PATH -ArgumentList "`"$pbixPath`"" -WindowStyle Hidden
              Write-Host "✅ Power BI Desktop Store version launch initiated"
              
              # Wait a bit and check if process started
              Start-Sleep -Seconds 10
              $pbiProcess = Get-Process -Name "PBIDesktop" -ErrorAction SilentlyContinue
              if ($pbiProcess) {
                Write-Host "✅ Confirmed Power BI Desktop is running (PID: $($pbiProcess.Id))"
              } else {
                Write-Host "⚠️ Could not immediately confirm Power BI Desktop started, but continuing..."
              }
            } else {
              Write-Error "❌ Unknown Power BI Desktop type: $($env:PBI_DESKTOP_TYPE)"
              exit 1
            }
          } catch {
            Write-Error "❌ Failed to launch Power BI Desktop: $_"
            Write-Host "Attempted to launch: $($env:PBI_DESKTOP_PATH)"
            Write-Host "With file: $pbixPath"
            exit 1
          }
          
          # Wait for Power BI Desktop to fully load
          Start-Sleep -Seconds 60
          Write-Host "⏳ Waiting for Power BI Desktop to fully initialize..."
          
          # Verify Power BI Desktop is running
          $pbiProcess = Get-Process -Name "PBIDesktop" -ErrorAction SilentlyContinue
          if ($pbiProcess) {
            Write-Host "✅ Power BI Desktop is running (PID: $($pbiProcess.Id))"
          } else {
            Write-Error "❌ Power BI Desktop process not found - it may have failed to start"
            exit 1
          }

          # Get the msmdsrv.exe port with retry logic
          $maxAttempts = 5
          $attempt = 0
          $msmdsrvPorts = $null
          
          do {
            $attempt++
            Write-Host "Attempt $attempt to find Analysis Services port..."
            $msmdsrvPorts = Get-Process -Name msmdsrv -ErrorAction SilentlyContinue | ForEach-Object {
              Get-NetTCPConnection -OwningProcess $_.Id -ErrorAction SilentlyContinue | Select-Object LocalPort -Unique
            }
            if (-not $msmdsrvPorts) {
              Start-Sleep -Seconds 10
            }
          } while (-not $msmdsrvPorts -and $attempt -lt $maxAttempts)
          
          if ($msmdsrvPorts) {
            # Extract PowerQuery functions schema
            $port = $msmdsrvPorts[0].LocalPort
            Write-Host "Found Analysis Services on port: $port"
            
            # Ensure output directory exists
            $outputDir = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath "pq_functions_schema"
            if (-not (Test-Path $outputDir)) {
              New-Item -ItemType Directory -Path $outputDir -Force
            }
            
            $outputJsonFile = Join-Path -Path $outputDir -ChildPath "pq_schema.json"
            Write-Host "Extracting to: $outputJsonFile"
            
            # Run extraction script with error handling
            try {
              pwsh -File ./.github/scripts/generate-doc-output.ps1 -port $port -outputJsonFile $outputJsonFile
              
              # Verify output file was created
              if (Test-Path $outputJsonFile) {
                $fileSize = (Get-Item $outputJsonFile).Length
                Write-Host "✅ Schema extraction successful! File size: $fileSize bytes"
              } else {
                Write-Error "❌ Output file was not created"
                exit 1
              }
            } catch {
              Write-Error "❌ Extraction script failed: $_"
              exit 1
            }
          } else {
            Write-Error "❌ No Analysis Services process found after $maxAttempts attempts"
            exit 1
          }
          
          # Close Power BI Desktop properly
          Write-Host "🧹 Cleaning up Power BI Desktop processes..."
          $pbiProcesses = Get-Process -Name "PBIDesktop" -ErrorAction SilentlyContinue
          if ($pbiProcesses) {
            $pbiProcesses | ForEach-Object {
              Write-Host "Stopping Power BI Desktop process (PID: $($_.Id))"
              Stop-Process -Id $_.Id -Force -ErrorAction SilentlyContinue
            }
            Start-Sleep -Seconds 5
            
            # Verify cleanup
            $remainingProcesses = Get-Process -Name "PBIDesktop" -ErrorAction SilentlyContinue
            if ($remainingProcesses) {
              Write-Host "⚠️ Some Power BI Desktop processes still running"
            } else {
              Write-Host "✅ All Power BI Desktop processes stopped"
            }
          } else {
            Write-Host "ℹ️ No Power BI Desktop processes found to clean up"
          }
          
          Write-Host "🎉 PowerQuery functions schema extraction completed successfully!"
      - name: Handle changes based on trigger type
        run: |
          # Determine trigger type
          $triggerType = "${{ github.event_name }}"
          Write-Host "🔍 Workflow triggered by: $triggerType"
          
          # Configure git
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Check for changes using PowerShell
          $gitStatus = git status --porcelain pq_functions_schema/
          if ([string]::IsNullOrEmpty($gitStatus)) {
            Write-Host "📝 No changes detected in PowerQuery functions schema"
          } else {
            Write-Host "📝 Changes detected in PowerQuery functions schema"
            
            if ($triggerType -eq "schedule") {
              # Auto-commit for scheduled runs (monthly updates)
              Write-Host "🤖 Auto-committing scheduled schema update..."
              git add pq_functions_schema/
              $commitDate = Get-Date -Format 'yyyy-MM-dd'
              git commit -m "🔄 Auto-update PowerQuery functions schema - $commitDate [skip ci]"
              git push origin HEAD
              Write-Host "✅ Scheduled update committed and pushed to main branch!"
              
            } elseif ($triggerType -eq "push") {
              # For push-triggered runs, create a PR instead of direct commit
              Write-Host "📋 Creating pull request for push-triggered schema update..."
              git add pq_functions_schema/
              $commitDate = Get-Date -Format 'yyyy-MM-dd'
              $branchName = "schema-update-$commitDate"
              git checkout -b $branchName
              git commit -m "🔄 Update PowerQuery functions schema - $commitDate"
              git push origin $branchName
              Write-Host "✅ Changes pushed to branch: $branchName"
              Write-Host "👉 Please create a PR to merge these changes"
              
            } elseif ($triggerType -eq "workflow_dispatch") {
              # For manual runs, ask user what to do
              Write-Host "🔧 Manual run detected - creating update branch..."
              git add pq_functions_schema/
              $commitDate = Get-Date -Format 'yyyy-MM-dd'
              $branchName = "manual-schema-update-$commitDate"
              git checkout -b $branchName
              git commit -m "🔄 Manual PowerQuery functions schema update - $commitDate"
              git push origin $branchName
              Write-Host "✅ Changes pushed to branch: $branchName"
              Write-Host "👉 Please review and create a PR to merge these changes"
              
            } else {
              Write-Host "❓ Unknown trigger type: $triggerType"
              Write-Host "📁 Changes are available but not committed"
            }
          }

